### ISSUE TITLE
Impossibile aggiungere un nuovo ente

### ISSUE THREAD

**Issue by marangiom** [AgID/wai-portal#1331]
segnalo che in https://webanalytics.italia.it/public-administrations/add inserisco i dati della nuova amministrazione che vorrei aggiungere, clicco su "aggungi sito" ma l'amministrazione non viene aggiunta e non accade nulla, nessun errore
grazie

**Comment by RCPrato** [comment]
Anche noi abbiamo lo stesso problema. Non ci fa aggiungere l'amministrazione

**Comment by pdavide** [comment]
Ciao @marangiom e @RCPrato,
per questo tipo di problematiche è necessario contattare l'assistenza all'indirizzo [wai@agid.gov.it](mailto:wai@agid.gov.it).
