### ISSUE TITLE
Impossibile aggiungere un nuovo sito

### ISSUE THREAD

**Issue by francescomugnai** [AgID/wai-portal#1412]
Buongiorno,

da stamattina non riesco ad aggiungere nuovi siti, va sempre in 504 Gateway Time-out (chiamando /websites/store).
Me l'ha fatto random anche qualche settimana fa ma poi si è risolto dopo qualche tentativo. Oggi invece non si sblocca. 

Potreste verificare per cortesia? Grazie mille.

**Comment by pdavide** [comment]
Ciao @francescomugnai,
per questo tipo di problematiche è necessario contattare l'assistenza all'indirizzo wai@agid.gov.it.

**Comment by francescomugnai** [comment]
> Ciao @francescomugnai, per questo tipo di problematiche è necessario contattare l'assistenza all'indirizzo [wai@agid.gov.it](mailto:wai@agid.gov.it).

Ciao Davide, grazie per il rapido feedback. 
Ho scritto un'oretta fa a quell'indirizzo per segnalare il problema.
