### ISSUE TITLE
Widget non funzionanti

### ISSUE THREAD

**Issue by MarcoTesta-EP** [AgID/wai-portal#1440]
Buongiorno,
Ho fatto per il comune di Cuorgnè (TO) una pagina dove mostrare i widgets con le statistiche, il codice è quello preso dal pannello di WAI, ma i widget non funzionano, come mai?
La pagina è raggiungibile a questo url: https://www.comune.cuorgne.to.it/it-it/statistiche-wai
Grazie.

P.S.: so che scrivere qui per questo genere di segnalazioni è il metodo errato, mi chiederete di mandare una mail a wai@agid.it, cosa che ho fatto il 26 Maggio e ripetute altre volte fino ad oggi senza alcuna risposta... grazie!

**Comment by pdavide** [comment]
Ciao @MarcoTesta-EP,
vedo che conosci la procedura ;-)
La mail corretta è wai@agid.gov.it.

Chiudo la issue.

**Comment by MarcoTesta-EP** [comment]
Ciao @pdavide, 
certo conosco la procedura, spero che questo serva come stimolo ad ottenere risposte alle svariate mail (ho scritto male, ho mandato tutte le mail a wai@agid.gov.it) che ho inviato, non ottenere risposte è veramente frustrante...
