### ISSUE TITLE
Risposte alle mail...

### ISSUE THREAD

**Issue by MarcoTesta-EP** [AgID/wai-portal#1444]
Buongiorno,
riscrivo nuovamente anche se so che non è il canale corretto ma purtroppo non ho alternative: sia noi che alcuni nostri clienti abbiamo scritto a wai@agid.gov.it segnalando problemi vari (alcuni diversi giorni fa) e non abbiamo ricevuto risposte, chiedo gentilmente di verificare...
Grazie.

Marco Testa

**Comment by pdavide** [comment]
@MarcoTesta-EP aprire continuamente issue su GitHub, quando è stato già chiarito che questo non è il canale corretto per le richieste di assistenza, mi sembra solo una perdita di tempo accompagnata da un uso non corretto di uno strumento adatto ad altri tipi di interazione.

**Comment by MarcoTesta-EP** [comment]
Concordo e non lo farò più, ma era l'unico modo a disposizione per sollecitare il controllo e le risposte sullo strumento da voi indicato, ovvero la mail wai@agid.gov.it
