### ISSUE TITLE
Problemi con l'accesso alle funzionalità della piattaforma

### ISSUE THREAD

**Issue by michelefiaschi** [AgID/wai-portal#1454]
Buongiorno,

sono amministratore del profilo del mio ente, da qualche giorno non riesco ad accedere alle funzionalità.
- effettuo il login con spid
- risulto loggato correttamente
- quando cerco di accedere alle funzioni della piattaforma ottengo l'errore

"Accesso con SPID
La pagina che hai richiesto è raggiungibile solo dopo l'autenticazione.

Usa il bottone 'Entra con SPID' che trovi in alto a destra nella pagina.
Se avevi già effettuato l'accesso è probabile che la tua sessione sia scaduta per inattività."

Anche la funzione di disconessione (e le altre sul profilo) non funzionano. 
Ho provato a farmi sospendere e riattivare l'account da un collega e ad usare browser diversi o navigazione anonima, stesso risultato.

**Comment by pdavide** [comment]
Ciao @michelefiaschi,
se il tuo provider SPID è Infocert, si tratta di un bug che abbiamo già identificato è corretto.
Il fix sarà rilasciato in settimana.

**Comment by michelefiaschi** [comment]
Buongiorno,

confermo che il provider è infocert, attendo allora il fix.

grazie,
Michele

---
*Michele Fiaschi*
Responsabile Servizio Sistemi Informativi | Area progetti e servizi ICT
<http://ict.sns.it>
Scuola Normale Superiore
Tel.   +39 050 509.662
***@***.***



Il giorno mar 28 giu 2022 alle ore 10:32 Davide Porrovecchio <
***@***.***> ha scritto:
