### ISSUE TITLE
Conteggio utenti / azioni in tempo reale

### ISSUE THREAD

**Issue by elcoda** [AgID/wai-portal#1456]
Buongiorno,
da stamane sto riscontrando un problema sul conteggio degli utenti/azioni in tempo reale.
Il numero riportato è sempre zero sebbene poi i dettagli delle "visite in tempo reale" vengano riportati ma - a quanto posso capire - con un certo ritardo.
Sembra ci sia una sorta di ritardo nell'acquisizione del dato non so se lato WAI, possibile?

Grazie mille

**Comment by pdavide** [comment]
Ciao @elcoda, la funzionalità di conteggio degli utenti/azioni in tempo reale non va considerata al momento come affidabile proprio perché potrebbe essere aggiornata con ritardo come da te rilevato. È possibile che in futuro sarà rimossa da WAI.

Per domande generiche come la tua, consiglio di di usare il canale #design-analytics del workspace Developers Italia su Slack.
