### ISSUE TITLE
Selezione date personalizzata

### ISSUE THREAD

**Issue by rizrob66** [AgID/wai-portal#1467]
Buongiorno, 
non ho trovato il modo di fare una selezione di date personalizzata tipo dal 10/6/22 al 20/6/22.
Potete aiutarmi?

grazie

**Comment by pdavide** [comment]
Ciao @rizrob66,
non è possibile selezionare intervalli di date arbitrari.
Si possono selezionare giorni singoli, settimane, mesi o anni.
