### ISSUE TITLE
Stato "In attesa" si protrae per troppo tempo 

### ISSUE THREAD

**Issue by savdav96** [AgID/wai-portal#1501]
Salve a tutti!
Il sito che sto gestendo è un'applicazione web scritta in React. 
Per la gestione di WAI ho prima utilizzato lo snippet (inserendolo nell'header dell'index.html) e poi utilizzato la libreria `@datapunt/matomo-tracker-react` senza usare propriamente lo snippet fornito (loggando le chiamate di inizializzazione effettuate, queste risultano uguali). 
Il sito, però non si attiva in entrambi i casi e non ho feedback al riguardo.

Tutto è stato effettuato dall'ambiente di sviluppo del sito **ovvero localhost**, che ovviamente non corrisponde al sito indicato nella pagina di WAI. La mia domanda è se, affinchè l'attivazione proceda, sia il vostro backend che debba "pingare" l'effettiva esistenza del sito _(e quindi occorre che questo sia effettivamente hostato nel dominio indicato e che risponda)_, oppure che la comunicazione avvenga solo dal sito istituzionale verso il backend di matomo _(in tal caso non saprei quale sia l'errore riscontrato)._
Inoltre volevo chiedere quali fossero i parametri corretti da inserire nella config di matomo, essendo che per React è più funzionale utilizzare la libreria fornita (anche per loggare eventi), e non lo snippet. 
Di seguito allego la init dell'istanza come da [https://www.npmjs.com/package/@datapunt/matomo-tracker-react](guida)

```
const instance = createInstance({
  urlBase: 'https://LINK.TO.DOMAIN',
  siteId: 3,
  userId: 'UID76903202', // optional, default value: `undefined`.
  trackerUrl: 'https://LINK.TO.DOMAIN/tracking.php', // optional, default value: `${urlBase}matomo.php`
  srcUrl: 'https://LINK.TO.DOMAIN/tracking.js', // optional, default value: `${urlBase}matomo.js`
  disabled: false, // optional, false by default. Makes all tracking calls no-ops if set to true.
  heartBeat: { // optional, enabled by default
    active: true, // optional, default value: true
    seconds: 10 // optional, default value: `15
  },
  linkTracking: false, // optional, default value: true
  configurations: { // optional, default value: {}
    // any valid matomo configuration, all below are optional
    disableCookies: true,
    setSecureCookie: true,
    setRequestMethod: 'POST'
  }
})
```

**Comment by pdavide** [comment]
Ciao @savdav96,
le chiamate vengono registrate come visite solo se provengono dal dominio impostato in WAI. Se chiami da localhost è normale che non siano prese in considerazione. Il concetto di "sito attivo" è proprio questo, quindi provare a renderlo attivo se non è ancora online e disponibile al pubblico non ha senso.
Per quanto riguarda la configurazione, direi che è sufficiente impostare `urlBase: 'https://ingestion.webanalytics.italia.it/'` e `siteId` coerentemente a quanto trovi nello snippet dello specifico sito. Il campo `userId` dovrebbe essere lasciato vuoto o `undefined`.

**Comment by pdavide** [comment]
Chiudo la issue e aggiorno il titolo il modo da aiutare chi dovesse cercare info sull'integrazione con React.

**Comment by savdav96** [comment]
Grazie mille per il supporto. Suggerisco forse di scrivere questa informazione nelle FAQ - ho trovato qualche altra persona che era in dubbio sul canale Slack - . 
Un'ultima informazione: ho notato che esistono due `siteId` , uno solo numerico (che essendo solo di quattro cifre penso sia "interno" alla propria PA) e un'altro alfanumerico (che sembra più essere un digest pubblico univoco). Nella libreria, tipizzata, è richiesto un `number` . Quale occorre?

**Comment by pdavide** [comment]
Ciao @savdav96,
le FAQ saranno aggiornate a breve e aggiungeremo anche le info di questa issue, come suggerisci.

Per quanto riguarda il `siteId`, la libreria lo tipizza in modo errato come `number`, infatti non è obbligatorio che lo sia. Per fortuna è comunque possibile chiedere la "versione number" corrispondente al `siteId` alfanumerico inviando una mail a wai@agid.gov.it.
