### ISSUE TITLE
assenza di tracciamenti da luglio 2022

### ISSUE THREAD

**Issue by marangiom** [AgID/wai-portal#1541]
dalla dashboard risultano 0 visite su tutti i siti configurati e attivati; sembra che le tracciature non arrivino alla dashboard o non vengano proprio registrate

**Comment by White-Seraph** [comment]
Ci sono novità in merito?
Anche i nostri siti sono fermi con il tracciamento statistiche.

**Comment by pdavide** [comment]
## Comunicazione importante

https://webanalytics.italia.it/#comunicazione-potenziamento.
