### ISSUE TITLE
Problema di tracciamento dei download

### ISSUE THREAD

**Issue by dmargagliotta** [AgID/wai-portal#1903]
Abbiamo fatto dei test sulla corretta tracciatura del numero dei download e questo sembra non coincidere con il numero di download effettivamente fatti.
Ipotizando un ritardo nella tracciatura da parte di WAI abbiamo riverificato il numero di download dopo 1 ora e questo non era cambiato.
Non ci è chiaro se non vengono contati correttamente o se bisogna considerare un ritardo ancora maggiore nella registrazione dei dati rispetto a quando avviene l'evento.
Grazie,

**Comment by pdavide** [comment]
Per problematiche di questo genere, si consiglia di scrivere all'indirizzo wai@agid.gov.it specificando tutti i dettagli necessari a identificare la criticità riscontrata.
