### ISSUE TITLE
Cambiato URL portale istituzionale non recepito da WAI e non modificabile

### ISSUE THREAD

**Issue by ilbassa** [AgID/wai-portal#1905]
Buongiorno, abbiamo cambiato il portale istituzionale da [web.unipv.it](http://web.unipv.it/) a [portale.unipv.it](http://portale.unipv.it/)
La modifica è stata fatta anche sulla scheda IPA.

WAI non ha recepito la modifica per cui abbiamo aggiunto un nuovo sito web con url https://portale.unipv.it/
Vorrei ora modificare i permessi sul sito portale.unipv.it, ma in modifica mi dice che l'url è già utilizzato da un'altra PA.

Come possiamo fare?

**Comment by pdavide** [comment]
Ciao @ilbassa,
la risposta è stata fornita sul canale mail, che è il più indicato per questo tipo di richieste.

Chiudo la issue.
