### ISSUE TITLE
Supportare gli ambienti previsti nel portale

### ISSUE THREAD

**Issue by pdavide** [AgID/wai-portal#387]
```suggestion
     APP_ENV={{ wai_portal_environments[item] }}
```

_Originally posted by @pdavide in https://github.com/pdavide/wai-infrastructure/pull/96_

**Comment by pdavide** [comment]
- Impostare funzionalità di auto-reset per public-playground
- Permettere l'attivazione di siti primari non listati su IPA (es. collaudo)

**Comment by Valair** [comment]
@pdavide credo sia necessario coinvolgere anche @giafar in merito al reset.
Lato portale potremmo far girare le `migration:fresh`, svuotare i db di redis e ricreare gli indici utenti e siti web. Rimarrebbe poi il seeding del super admin e del sito webanalytics che, meno di non fare le `select` prima del drop per recuperare i valori, viene fatto da ansible.
Lato matomo andrebbe scritto un plugin (installato solo su playground) che esegua una cosa simile al `createTable` del plugin installation (senza verificare la presenza di tabelle da riusare), ma anche in questo caso non avrei modo di fare seeding (sempre a meno di non fare select prima); fatto questo andrebbe poi lanciato l'evento di `install` ai plugin aggiuntivi (queuetracking, disabletracking ad esempio) per creare le loro table.

**Comment by pdavide** [comment]
Per quanto riguarda il portale forse si potrebbe creare un comando da chiamare mediante un CronJob di K8S che si occupi di:
- `artisan migrate:fresh`
- `artisan db:seed` (il super admin è già impostato mediante env vars; il sito webanalytics hardcoded dovremmo abbandonarlo in tutti gli ambienti e lasciare che si possa inserire come un sito tematico dall'amministratore della PA AGID).
- `artisan view:clear`
- `artisan route:clear`
- `artisan config:clear`
- `artisan cache:clear`
- reset delle sessioni mediante cancellazione del db redis corrispondente

Si dovrebbe anche mostrare un countdown (in giorni e ore) nella fascia highlight in alto.

Per quanto riguarda matomo:
Si potrebbe tagliare la testa al toro creando uno script/plugin che prenda in pasto il dump creato da ansible (lo potremmo caricare nel CronJob come configmap @giafar)?
A seguire installazione plugin aggiuntivi.

Che ne pensi?

**Comment by Valair** [comment]
> Si potrebbe tagliare la testa al toro creando uno script/plugin che prenda in pasto il dump creato da ansible (lo potremmo caricare nel CronJob come configmap @giafar)?
A seguire installazione plugin aggiuntivi.

Sì, potremmo decidere una cartella all'interno del plugin, al cui interno ci sono tutti i dump montati da configmap, compresi quelli dei plugin aggiuntivi (stabiliamo uno standard in modo che possa prendere prima quello del db generale, poi gli altri) in modo da non dover richiamare nessun `install`.
Il plugin quindi esegue semplicemente `Db::droppAllTables()` seguito dai `Db::exec()` coi dump.
Senza scomodare la schedulazione di un task, per lanciare il tutto definiamo un comando console, quindi il cronjob parte, si installa il plugin e lancia quel comando come fa ora per eseguire il `core:archive`.
Se anche per @giafar è ok direi che potremmo procedere su questa linea.

**Comment by pdavide** [comment]
Rispetto al flush di redis teniamo conto che il nostro chart helm prevede che i comandi `FLUSHDB` e `FLUSHALL` siano disabilitati. Questo causa il fatto che `artisan cache:clear` termina con un errore.

**Comment by giafar** [comment]
> lo potremmo caricare nel CronJob come configmap @giafar

In realtà al dump dovremmo accodare gli script dei plugin in modo da ottenere un unico file con il quale creare la config map per il job: si può fares :-).

**Comment by Valair** [comment]
Ho creato un [branch](https://github.com/AgID/wai-portal/tree/environments_support) in cui ho iniziato il supporto.
- `public-playground`: task schedulato che esegue il reset dell'ambiente e countdown nell'highlight bar
- flag `custom_public_administrations` configurabile via env `APP_CUSTOM_PUBLIC_ADMINISTRATIONS_ENABLED` per includere le rotte di creazione di una PA custom

**Comment by axciccu** [comment]
Completate le verifiche sulle funzionalità e i relativi test. Manca ancora la parte in cui si dice a Matomo di non fare il controllo sul dominio. @pdavide Magari su questo punto ci sentiamo così apro una pr

**Comment by pdavide** [comment]
> Completate le verifiche sulle funzionalità e i relativi test. Manca ancora la parte in cui si dice a Matomo di non fare il controllo sul dominio. @pdavide Magari su questo punto ci sentiamo così apro una pr

Sul controllo da parte di Matomo dovremmo essere già a  posto con: https://github.com/AgID/wai-portal/blob/develop/app/Services/MatomoService.php#L107-L109

Magari fai una verifica in locale per vedere se è a posto così.

**Comment by pdavide** [comment]
Closed in #567.
