### ISSUE TITLE
Limitare l'accesso alla beta ad un insieme definito di PA

### ISSUE THREAD

**Issue by pdavide** [AgID/wai-portal#488]
Dovrebbe essere implementata una funzionalità whitelist con le seguenti caratteristiche:
- attivabile/disattivabile da `config.wai.closed_beta` valorizzato da env;
- implementazione come file yaml `closed_beta_whitelist.yml`;
- il file `closed_beta_whitelist.yml` dovrebbe essere aggiornato automaticamente dal repo mediante webhook github corrispondente al push su master;
- si potrebbe usare il package https://github.com/spatie/laravel-webhook-client (senza memorizzazione su db delle chiamate)
- lato ux quando si seleziona una PA non in whitelist dovrebbe apparire una modale informativa
- lato server dovrebbe essere fatto un check in fase di validazione della request

**Comment by Valair** [comment]
> implementazione come file yaml closed_beta_whitelist.yml;

La struttura è semplicemente un elenco di codici IPA?
```
ipa_code:
  - ...
  - ...
```

> si potrebbe usare il package https://github.com/spatie/laravel-webhook-client (senza memorizzazione su db delle chiamate)

Possiamo usare quella libreria, ma non è possibile escludere il salvataggio nel db; la configurazione prevede l'uso di un job che estenda [ProcessWebhookJob](https://github.com/spatie/laravel-webhook-client/blob/master/src/ProcessWebhookJob.php), quindi necessariamente pushato sulla coda (Redis nel nostro caso), rendendo obbligatorio il salvataggio su DB della [WebhookCall](https://github.com/spatie/laravel-webhook-client/blob/master/src/Models/WebhookCall.php), che non è altro che un Eloquent Model, per serializzazione/deserializzazione.
Il service provider verifica che che si usino sotto-classi di quelle indicate: per alterarne il funzionamento andrebbero riscritti troppi componenti.

**Comment by pdavide** [comment]
Per non salvare le chiamate su DB pensavo che si potrebbe fare così (correggimi se sbaglio):
- usare una classe figlia di `WebhookCall` che non effettui salvataggi sul DB;
- usare un'implementazione di `ProcessWebhookJob` che prenda quindi come parametro del costruttore il model, ma che poi non lo salvi in una proprietà dell'oggetto (vincolandoci quindi al DB per motivi di serializzazione) optando invece per avere un semplice array con le info che ci servono per eseguire il job quando esce dalla coda;

Che ne pensi?

**Comment by Valair** [comment]
Sì per il model è facile:

- `storeWebhook` chiama `make` invece di `create`
- gli altri due metodi ritornano `$this` senza fare nulla

Per il secondo punto, deve essere accettabile un piccolo workaround per cui il costruttore del job che estende `ProcessWebhookJob`, in realtà non richiama quello del `parent` in modo da non lanciare la serializzazione del model; la proprietà `$webhookCall` sarà presente ma non inizializzata.

**Comment by pdavide** [comment]
Closed in #504.
