### ISSUE TITLE
Aggiornamento framework

### ISSUE THREAD

**Issue by pdavide** [AgID/wai-portal#545]
Valutare l'impatto e i potenziali vantaggi di un aggiornamento a Laravel 7.
https://laravel.com/docs/7.x/upgrade

**Comment by axciccu** [comment]
Spid-Laravel non è compatibile con la versione di Laravel 7 a causa del trait `DetectsApplicationNamespace` che è stato rimosso e che viene usato in CommandExample.

https://github.com/italia/spid-laravel/blob/919e7de4d2231beab2bf5160d0a1a923ee205f9a/src/Console/CommandExample.php#L20

Cerco di capire come renderlo compatibile.

**Comment by axciccu** [comment]
Bisogna anche passare a PHP 7.4

**Comment by axciccu** [comment]
Ho aperto un [branch](https://github.com/AgID/wai-portal/tree/bump-version-laravel-7) dove ho praticamente completato il passaggio a Laravel 7.
Appena concluso apro una pull request.

**Comment by axciccu** [comment]
@pdavide ci sarebbe da creare una nuova release per spid-laravel in modo da poterla includere nel composer.json

**Comment by pdavide** [comment]
Closed in #665.
