### ISSUE TITLE
Inibire l'accesso degli utenti al modulo UsersManager

### ISSUE THREAD

**Issue by pdavide** [AgID/wai-portal#593]

**Comment by axciccu** [comment]
Creato un nuovo plugin [UsersManagerOnlyAdmin](https://github.com/AgID/wai-matomo-plugin-UsersManagerOnlyAdmin) che restringe l'accesso a UsersManager solo agli admin.
E integrato nel branch [users_manager_matomo_plugin](https://github.com/AgID/wai-portal/tree/users_manager_matomo_plugin) dove per ora prende direttamente develop. 
Da aggiungere una taggatura al plugin per controllare la versione.

**Comment by pdavide** [comment]
Closed in #641.
