### ISSUE TITLE
Aggiunta metadati opengraph e dati strutturati alle pagine

### ISSUE THREAD

**Issue by pdavide** [AgID/wai-portal#596]
Ogni pagina dovrebbe includere metadati opengraph e altri dati strutturati.
Alcuni link per dati strutturati che potrebbero essere rilevanti per WAI:
- https://developers.google.com/search/docs/data-types/breadcrumb?hl=it
- https://developers.google.com/search/docs/data-types/dataset?hl=it
- https://developers.google.com/search/docs/data-types/faqpage?hl=it
- https://developers.google.com/search/docs/data-types/how-to?hl=it
- https://developers.google.com/search/docs/data-types/logo?hl=it

**Comment by axciccu** [comment]
Iniziata l'implementazione dei dati strutturati nel branch [opengraph](https://github.com/AgID/wai-portal/tree/opengraph) 
Rimane da implementare il data-type dataset ma i contenuti sono raggiungibili solo da utente autenticato

**Comment by pdavide** [comment]
@axciccu il datatype dataset lo riserviamo per dopo, quando avremo una pagina pubblica con gli open data.

**Comment by pdavide** [comment]
Closed in #638.
