### ISSUE TITLE
Elenco amministrazioni in dashboard amministrativa

### ISSUE THREAD

**Issue by pdavide** [AgID/wai-portal#649]
Nella dashboard amministrativa dovrebbe apparire un elenco (datatable) di tutte le amministrazioni presenti su WAI con evidenza dello stato, dei siti web attivi/pending e un bottone per fare lo switch del tenant.

**Comment by axciccu** [comment]
Ho aggiunto [qui](https://github.com/AgID/wai-portal/tree/admin_dashboard_amministrazioni) la dashboard delle amministrazioni per i super admin.
Lo stato di ogni amministrazione è legata allo stato del suo admin, quindi nel datatable si trova quello stato in evidenza.
Ci sono da aggiungere alcuni test e poi procedo con la PR.

**Comment by pdavide** [comment]
Closed in #653.
