### ISSUE TITLE
Supporto a logging slack su più canali

### ISSUE THREAD

**Issue by pdavide** [AgID/wai-portal#658]
Il sistema di logging del portale dovrebbe supportare la possibilità di configurare più canali (anche in workspace separati) per l'invio dei log applicativi.

**Comment by axciccu** [comment]
@pdavide I log devono essere inviati su entrambi i canali in contemporanea?

**Comment by pdavide** [comment]
@axciccu si esatto

**Comment by axciccu** [comment]
La soluzione più immediata sarebbe quella di sdoppiare il canale slack per permettere la configurazione di un canale aggiuntivo.

```
# Logging stack
# -------------
LOG_STACK_CHANNELS=slack,slack2

# Slack notifications
# -------------------
LOG_SLACK_WEBHOOK_URL=
LOG_SLACK_USERNAME=

# Slack notifications additional channel
# -------------------
LOG_SLACK_WEBHOOK_URL_ADDITIONAL_CHANNEL=
LOG_SLACK_USERNAME_ADDITIONAL_CHANNEL=
```
