### ISSUE TITLE
Gestione errori widget in home

### ISSUE THREAD

**Issue by pdavide** [AgID/wai-portal#709]
I widget in home, in caso di anomalia di matomo, dovrebbero gestire l'errore in modo user friendly.

**Comment by axciccu** [comment]
Esiste un errore facilmente riproducibile?

**Comment by pdavide** [comment]
È sufficiente che imposti nginx per restituirti un errore alle richieste verso matomo.

**Comment by axciccu** [comment]
Però allora mi sfugge qualcosa. 
Se faccio restituire un errore ad nginx, l'iframe carica l'errore al suo interno senza che io possa renderlo più user friendly.
Invece se l'errore avviene su matomo potrei visualizzare un widget di errore
