### ISSUE TITLE
Gestione indirizzi email e check di unicità

### ISSUE THREAD

**Issue by pdavide** [AgID/wai-portal#777]
Dopo l'introduzione della relazione many-to-many tra utenti e amministrazioni, ha ancora senso mantenere questi controlli?
Inoltre la funzionalità è affetta da un bug per cui il check sul ruolo di super-admin è effettuato nello scope della singola amministrazione, impedendo la modifica dei permessi di un utente che è anche super-admin.

@axciccu mi daresti un'opinione su questo?

https://github.com/AgID/wai-portal/blob/60da540d808587c733177fe73fafff656c58a242/app/Http/Requests/StoreUserRequest.php#L61-L79

https://github.com/AgID/wai-portal/blob/60da540d808587c733177fe73fafff656c58a242/app/Http/Requests/UpdateUserRequest.php#L44-L50

**Comment by axciccu** [comment]
La prima criticità che mi viene in mente è che durante il processo di creazione dell'utente, con la mail indicata viene anche creato un utente su Matomo. Se perdiamo l'univocità dovremmo gestire il caso in cui un utente si registra con un CF mai utilizzato e una mail già utilizzata. In questo caso a quale utente sul portale dovrebbe essere collegato l'utente su matomo? 
Non so se ha senso rimuovere il check di univocità anche perché durante l'associazione di una nuova pa all'utente si ha la possibilità di inserire un indirizzo diverso usato solo per le comunicazioni.

Sul bug invece verifico e sposto lo scope.

**Comment by pdavide** [comment]
@axciccu dovremmo allargare un po' la issue alla gestione indirizzi email.
Rilevo le seguenti criticità:
- nella pagina utenti vedo la mail specifica della pa mentre nella pagina di modifica e di dettaglio utente vedo quella del profilo;
- il check di cui sopra dovrebbe applicarsi solo alla modifica della mail profilo (che impatta su matomo) e non a quella specifica della pa;
- il check, come attualmente previsto a meno del bug sullo scope, dovrebbe escludere eventuali duplicazioni della mail profilo (tabella users) con gli indirizzi dei super-admin i quali non hanno una corrispondente utenza matomo.

Sentiamoci se ti sembra che il mio ragionamento abbia qualche criticità.

**Comment by pdavide** [comment]
@axciccu aggiungo che, al cambio di indirizzo email, la mail di verifica ricevuta dall'utente arriva all'indirizzo sbagliato (dovrebbe essere quello del profilo e non quello specifico della PA).
Inoltre il testo e l'oggetto della mail dovrebbero essere differenti da quelli per la creazione di un nuovo account oppure dovrebbero essere modificati per essere sensati in entrambi i tipi di evento.

**Comment by axciccu** [comment]
ciao @pdavide, ricapitolando

- nella pagina utenti rimane l'indirizzo della pa
- in dettaglio e modifica utente (per la pa) faccio modificare l'indirizzo della pa
- il check di unicità rimane sull'indirizzo del profilo
- l'invio delle mail viene fatto sempre alla mail del profilo e va veririccato anche il testo

**Comment by pdavide** [comment]
@axciccu l’invio delle mail, di norma, va verso l’indirizzo specifico della PA.
All’indirizzo del profilo vanno inviate solo le mail relative alla verifica dell’indirizzo mail stesso.

**Comment by axciccu** [comment]
> @axciccu l’invio delle mail, di norma, va verso l’indirizzo specifico della PA.
> All’indirizzo del profilo vanno inviate solo le mail relative alla verifica dell’indirizzo mail stesso.

ok, chiaro

**Comment by pdavide** [comment]
Apro comunque una issue per valutare la possibilità di abbandonare del tutto la mail associata al profilo (tabella `users`).

**Comment by pdavide** [comment]
Closed in #815.
