### ISSUE TITLE
come visitatore vorrei vedere il range di riferimento nei widget homepage

### ISSUE THREAD

**Issue by tassoman** [AgID/wai-portal#787]
Ciao, nella homepage pubblica https://webanalytics.italia.it/ compaiono alcuni widget con dati di navigazione complessivi.
Purtroppo non è indicato a quale range si riferiscono i dati visibili.

Si potrebbe aggiungere una nota nel titolo: "Analytics degli ultimi 30 giorni" 

In alternativa, magari in seconda iterazione, si potrebbe integrare una combo box di selezione del periodo che abbia tra le opzioni disponibili i report generati, es: yesterday, week, month ecc...

**Comment by pdavide** [comment]
Closed in f530231db76beec4f925287d164f29b2a7c0eb6b.
