### ISSUE TITLE
Build dell'immagine di wai-portal e push su registry

### ISSUE THREAD

**Issue by pdavide** [AgID/wai-portal#8]

**Comment by Valair** [comment]
Ho creato un [branch](https://github.com/AgID/wai-portal/tree/github_actions) con le actions; per il funzionamento vanno creati due secrets nel repository, corrispondenti a nome utente e password per la login al registry:
- DOCKER_USERNAME 
- DOCKER_TOKEN

**Comment by axciccu** [comment]
@pdavide 
> Ho creato un [branch](https://github.com/AgID/wai-portal/tree/github_actions) con le actions; per il funzionamento vanno creati due secrets nel repository, corrispondenti a nome utente e password per la login al registry:
> 
> * DOCKER_USERNAME
> * DOCKER_TOKEN

Sono stati già inseriti i due secrets?
In ogni caso provando a lanciare la action si ottiene:
`Only actions in "AgID" are allowed for this repository`

**Comment by pdavide** [comment]
> Sono stati già inseriti i due secrets?

@axciccu token inseriti adesso.

**Comment by pdavide** [comment]
Closed in a1d65d2...8ccfa91.
